[project]
name = "physical-robot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "depthai>=3.6.1",
    "dotenv>=0.9.9",
    "grpcio>=1.80.0",
    "grpcio-tools>=1.80.0",
    "matplotlib>=3.10.9",
    "numpy>=2.4.4",
    "opencv-python>=4.13.0.92",
    "pydantic>=2.13.4",
    "redis>=7.4.0",
    "rerun-sdk==0.26.2",
    "scikit-image>=0.26.0",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "shapely>=2.1.2",
    "websockets>=16.0",
]

[tool.setuptools.packages.find]
where = ["."]           # Look in the current directory
include = ["physical_robot*"] # Only include the main package and its sub-packages
