syntax = "proto3";

package physical_robot;

// Messages
message LidarData {
    repeated float angles = 1;
    repeated float dists = 2;
    int64 timestamp = 3;
}

message Acknowledge {
    bool success = 1;
    string message = 2;
}

message MotionCommand {
    string motion_type = 1;
    float distance = 2;
}

message MotionDistance {
    float left_wheel_dist = 1;
    float right_wheel_dist = 2;
}

// Services
service RobotServer {
    rpc GetLatestLidarData(Acknowledge) returns (LidarData);

    rpc SendMotionCommand(MotionCommand) returns (MotionDistance);
}