syntax = "proto3";

package physical_robot;

// Messages
message LidarData {
    repeated float angles = 1;
    repeated float dists = 2;
    int64 timestamp = 3;
}

message Acknowledge {
    bool success = 1;
    string message = 2;
}

message MotionCommand {
    string motion_type = 1;
    float distance = 2;
}

message MotionDistance {
    float left_wheel_dist = 1;
    float right_wheel_dist = 2;
}

message NumpyArray {
    bytes img_bytes = 1;
    repeated int64 shape = 2;
    string type = 3;
}

message CameraData {
    NumpyArray rgb_img = 1;
    NumpyArray depth_img = 2;
    int64 timestamp = 3;
}

message PointCloudData {
    NumpyArray point_cloud_coords = 1;
    NumpyArray point_cloud_colors = 2;
    int64 timestamp = 3;
}

message IMUData {
    float accel_x = 1;
    float accel_y = 2;
    float accel_z = 3;

    float gyro_x = 4;
    float gyro_y = 5;
    float gyro_z = 6;
}

message OakdLiteData {
    CameraData camera_data = 1;
    IMUData imu_Data = 2;
    PointCloudData point_cloud_data = 3;
    int64 timestamp = 4;
}

message RobotMotorPositions {
    int64 motor_position_left = 1;
    int64 motor_position_right = 2;
}

message RobotMotorVelocities {
    int64 motor_velocity_left = 3;
    int64 motor_velocity_right = 4;
}

message RobotState {
    RobotMotorPositions positions = 1;
    RobotMotorVelocities velocities = 2;
    NumpyArray robot_state = 3;
}

message MonitoringState {
    LidarData lidar_data = 1;
    CameraData camera_data = 2;
    IMUData imu_data = 3;
    RobotState robot_state = 4;
}

// Services
service RobotServer {
    rpc GetLatestLidarData(Acknowledge) returns (LidarData);

    rpc GetLatestImageData(Acknowledge) returns (CameraData);

    rpc GetLatestIMUData(Acknowledge) returns (IMUData);

    rpc GetLatestOakdLiteData(Acknowledge) returns (OakdLiteData);

    rpc SendMotionCommand(MotionCommand) returns (MotionDistance);

    rpc GetMotorPositions(Acknowledge) returns (RobotMotorPositions);

    rpc GetMotorVelocities(Acknowledge) returns (RobotMotorVelocities);
}